### ISSUE TITLE
Dual Wielding other items?

### ISSUE THREAD

**Issue by This1Potato** [Provismet/Dual-Swords#5]
### Type of Suggestion

Modify Existing Functionality

### Description

Even though the mod's name is explicitly "Dual Swords", its functionality is amazing and I find interesting the possibility of adding the dual wield bonus damage to other items through the use of components.

### Reason

The request is mostly related to compatibility with Modular Item API and its official addon: Truly Modular Arsenal, which are incompatible with Dual Swords.

When speaking with the lead dev of those mods, Smartin, he said the incompatibility is caused by you calling item classes instead of item stacks (although tbh I didn't really understand, I'm no modder). As such, your mod would be incompatible with any kind of modular gear.

However, I propose the possibility of using components to decide wether an item uses or not the dual swords system, which (as far as I understand) should allow for more compatibility _and_ flexibility.

**Comment by Provismet** [comment]
There seems to be a slight misunderstanding here, but I'll try to explain as best I can.

In the same way that Modular Arsenal is part of the Truly Modular system, Dual Swords is part of the [Combat+ system](https://provismet.github.io/modding?tag=null&series=Combat%2B). Combat+ is a system built around allowing other mods to grant on-hit actions and intelligent enchantments.  
Dual Swords is really just adding onto this. In reality, the main feature of Dual Swords is not the offhand damage, but the offhand enchantments.

- Offhand damage and on-hit effects are controlled by a Combat+ interface called `DualWeapon`.
- The enchantments are controlled by a datapack tag called `combat-plus:dual_weapon`.

---

> Even though the mod's name is explicitly "Dual Swords"

Dual Swords is not dependent on swords. It specifically works with _dual weapons_, which is a category defined by Combat+. Swords just happen to be the only _dual weapons_ that exist in vanilla.  
For example, the daggers of [Additional Armoury](https://modrinth.com/mod/additional-armoury) are also _dual weapons_. This means that they also get the offhand damage when paired with Dual Swords.

---

> the possibility of adding the dual wield bonus damage to other items through the use of components

I'm going to assume you mean to make use of already existing components in vanilla. Dual Swords and Combat+ already do this. The offhand damage is part of the attribute component, and its value is based on the weapon's base damage (which is also part of that component).

---

> which are incompatible with Dual Swords

Upon reading the source code for [modular swords](https://github.com/Truly-Modular/Modular-Item-API/blob/main/common/src/main/java/smartin/miapi/item/modular/items/ModularSword.java). I believe they are fully incompatible with Dual Swords, and not just in regards to offhand damage.

The main feature of Dual Swords is the ability to _use_ the offhand weapons. Dual Swords enchantments add use-actions to weapons, but this depends on the item in question not already having a use-action. Swords from Modular Arsenal are hardcoded to use a configurable use-action, and they don't allow any data to pass through from their parent classes. This makes the two mods fully incompatible as it currently stands.

---

> calling item classes instead of item stacks

He's half right here. To set the offhand damage, I use an interface. Combat+ defines an interface called `DualWeapon`. By default only the class for vanilla swords uses this interface, but as seen with the daggers, this is by no means limited to swords. Any item can use the interface.

I use the base components inherent to the item, rather than those on the item stack. This means that they can be overriden by the user, which is the ideal behaviour because it allows for better customisability.  
It's certainly possible to use the components on the stack itself, but it raises several questions about its implementation, especially how and when to update the offhand damage attribute.

---

> should allow for more compatibility and flexibility

Due to the reasons outlined above, no, I don't believe it will.

You or Smartin are more than welcome to try and change my mind on this, there could simply be something that I'm not seeing. But as it stands, I don't believe swapping to item stack components would solve anything, and it could easily cause incompatibilities with far more mods.

---

Lastly, in regards to your specific usecase with the `modular_sword` items. I don't think you'll find a satisfying compatibility between the two mods without them both being reworked internally for that aim specifically. My attributes are bound to item objects and not itemstack objects, and Modular Arsenal's use-actions are bound to config files and not code values.

**Comment by Smartin-b** [comment]
The compatiblity concerns 1.20, not 1.21, Truly Modular hasnt finished porting to 1.21 yet.

As far as my understanding goes, the detection for swords should work via the interface, that should still be applied to Truly Modulars swords, but their offhand damage isnt calculated correctly.

i would suggest to swap to fabrics Attribute event for 1.20, as its a much safer way to adjust attributes, this way other mods enchantments and modiferies would still be respected, and would work with truly modulars swords.

**Comment by Provismet** [comment]
Wasn't aware of the event until now, thanks. Using the event solves the initial problem in a not-so-neat way, where all modular swords have an offhand bonus of +2.5 damage (for reference, Netherite only has a +2 bonus).

Combat+ wasn't stack-aware in 1.20.1, so I'll have to backport a few things. Will update on this later.

**Comment by Provismet** [comment]
This is now fixed as of version 1.1.2 for 1.20-1.20.4, but be advised that this only solves the offhand attribute issue.

Modular swords are still incompatible with the actual dual-wielding mechanics: parrying and lunging. This is because they don't call the super-method for use-actions. Daisho damage doesn't require use-actions to function, so that one should still work.

**Comment by Provismet** [comment]
Note: When testing the build, I encountered a crash within Modular Item API (specifically one of its dependencies). It only happened once and didn't reoccur ever again, even with the same environment. But, I've documented it [here](https://github.com/Truly-Modular/Modular-Item-API/issues/57) for you in case it's worth addressing.

**Comment by Smartin-b** [comment]
Thank you for the quick response, we already changed the code for the abilities, we just havent release the update yet.
The issue with nucleus is weird, that can only be triggered by something subscribing to the dmg event while its beeing executed?
Afaik we dont do that, but the developer of nucleus is working with miapi, so updating that shouldnt be a huge problem
